# Generated by Django 5.0.6 on 2024-07-02 06:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_social_id', models.CharField(max_length=20, unique=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_suspended', models.BooleanField(default=False)),
            ],
        ),
    ]
