# Generated by Django 5.0.6 on 2024-07-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
